BASE_PERMISSIONS = [
    {
        "code": "encomiendas.read",
        "name": "Leer encomiendas",
        "description": "Consultar encomiendas internas.",
        "module": "encomiendas",
        "action": "read",
    },
    {
        "code": "encomiendas.write",
        "name": "Crear encomiendas",
        "description": "Registrar encomiendas presenciales.",
        "module": "encomiendas",
        "action": "write",
    },
    {
        "code": "encomiendas.update",
        "name": "Actualizar encomiendas",
        "description": "Editar datos de encomiendas permitidas por regla de negocio.",
        "module": "encomiendas",
        "action": "update",
    },
    {
        "code": "encomiendas.cancel",
        "name": "Anular encomiendas",
        "description": "Anular logicamente encomiendas con motivo.",
        "module": "encomiendas",
        "action": "cancel",
    },
    {
        "code": "encomiendas.deliver",
        "name": "Entregar encomiendas",
        "description": "Registrar entrega final de encomiendas.",
        "module": "encomiendas",
        "action": "deliver",
    },
    {
        "code": "cotizaciones.calculate",
        "name": "Calcular cotizaciones",
        "description": "Calcular tarifas de encomiendas.",
        "module": "cotizaciones",
        "action": "calculate",
    },
    {
        "code": "cotizaciones.read",
        "name": "Leer cotizaciones",
        "description": "Consultar resultados de cotizacion.",
        "module": "cotizaciones",
        "action": "read",
    },
    {
        "code": "sunat.emit",
        "name": "Emitir SUNAT",
        "description": "Emitir boletas electronicas desde encomiendas.",
        "module": "sunat",
        "action": "emit",
    },
    {
        "code": "sunat.read",
        "name": "Leer SUNAT",
        "description": "Consultar informacion SUNAT.",
        "module": "sunat",
        "action": "read",
    },
    {
        "code": "sunat.download_pdf",
        "name": "Descargar PDF SUNAT",
        "description": "Descargar PDF de comprobantes.",
        "module": "sunat",
        "action": "download_pdf",
    },
    {
        "code": "etiquetas.generate",
        "name": "Generar etiquetas",
        "description": "Generar etiquetas y codigos QR.",
        "module": "etiquetas",
        "action": "generate",
    },
    {
        "code": "etiquetas.read",
        "name": "Leer etiquetas",
        "description": "Consultar informacion de etiquetas.",
        "module": "etiquetas",
        "action": "read",
    },
    {
        "code": "tracking.read",
        "name": "Leer tracking",
        "description": "Consultar seguimiento de encomiendas.",
        "module": "tracking",
        "action": "read",
    },
    {
        "code": "tracking.update_status",
        "name": "Actualizar tracking",
        "description": "Actualizar estados operativos de tracking.",
        "module": "tracking",
        "action": "update_status",
    },
    {
        "code": "users.read",
        "name": "Leer usuarios",
        "description": "Consultar usuarios internos.",
        "module": "users",
        "action": "read",
    },
    {
        "code": "users.write",
        "name": "Crear usuarios",
        "description": "Crear usuarios internos.",
        "module": "users",
        "action": "write",
    },
    {
        "code": "users.update",
        "name": "Actualizar usuarios",
        "description": "Actualizar usuarios internos y asignar roles.",
        "module": "users",
        "action": "update",
    },
    {
        "code": "users.disable",
        "name": "Desactivar usuarios",
        "description": "Desactivar usuarios internos.",
        "module": "users",
        "action": "disable",
    },
    {
        "code": "roles.read",
        "name": "Leer roles",
        "description": "Consultar roles.",
        "module": "roles",
        "action": "read",
    },
    {
        "code": "roles.write",
        "name": "Crear roles",
        "description": "Crear roles dinamicos.",
        "module": "roles",
        "action": "write",
    },
    {
        "code": "roles.update",
        "name": "Actualizar roles",
        "description": "Actualizar o desactivar roles.",
        "module": "roles",
        "action": "update",
    },
    {
        "code": "roles.assign_permissions",
        "name": "Asignar permisos a roles",
        "description": "Gestionar permisos asociados a roles.",
        "module": "roles",
        "action": "assign_permissions",
    },
    {
        "code": "permissions.read",
        "name": "Leer permisos",
        "description": "Consultar catalogo de permisos.",
        "module": "permissions",
        "action": "read",
    },
    {
        "code": "permissions.write",
        "name": "Crear permisos",
        "description": "Crear o actualizar permisos.",
        "module": "permissions",
        "action": "write",
    },
    {
        "code": "developer.read",
        "name": "Vista developer",
        "description": "Inspeccionar tablas del sistema en modo solo lectura y exportarlas.",
        "module": "developer",
        "action": "read",
    },
    {
        "code": "developer.write",
        "name": "Editar tablas (vista developer)",
        "description": "Crear, actualizar y eliminar filas desde la vista developer.",
        "module": "developer",
        "action": "write",
    },
    {
        "code": "optimization.read",
        "name": "Consultar optimizacion de carga",
        "description": "Consultar paquetes, camiones y escenarios de optimizacion.",
        "module": "optimization",
        "action": "read",
    },
    {
        "code": "optimization.run",
        "name": "Ejecutar optimizacion de carga",
        "description": "Ejecutar algoritmos de optimizacion y consultar sus resultados.",
        "module": "optimization",
        "action": "run",
    },
]

BASE_ROLE_PERMISSIONS = {
    "ADMINISTRADOR": [
        permission["code"]
        for permission in BASE_PERMISSIONS
        if not permission["code"].startswith(("optimization.", "developer."))
    ],
    "SECRETARIA": [
        "encomiendas.read",
        "encomiendas.write",
        "encomiendas.update",
        "encomiendas.cancel",
        "cotizaciones.calculate",
        "cotizaciones.read",
        "sunat.emit",
        "sunat.read",
        "sunat.download_pdf",
        "etiquetas.generate",
        "etiquetas.read",
        "tracking.read",
        "tracking.update_status",
    ],
    "ESTIBA": [
        "optimization.read",
        "optimization.run",
    ],
    "DEVELOPER": [
        "developer.read",
        "developer.write",
    ],
}

BASE_ROLE_DESCRIPTIONS = {
    "ADMINISTRADOR": "Acceso completo al sistema interno.",
    "SECRETARIA": "Gestiona registros, cotizaciones, boletas, etiquetas y tracking.",
    "ESTIBA": "Acceso exclusivo a la optimizacion y simulacion de carga.",
    "DEVELOPER": "Inspeccion tecnica de las tablas del sistema (solo lectura y exportacion).",
}
