PRE_REGISTERED_STATUS = "PRE_REGISTRADA"
REGISTERED_STATUS = "REGISTRADA"
QUOTED_STATUS = "COTIZADA"
PAYMENT_CONFIRMED_STATUS = "PAGO_CONFIRMADO"
RECEIPT_ISSUED_STATUS = "BOLETA_EMITIDA"
IN_TRANSIT_STATUS = "EN_TRANSITO"
AT_DESTINATION_STATUS = "EN_DESTINO"
DELIVERED_STATUS = "ENTREGADA"
CANCELED_STATUS = "ANULADA"

SHIPMENT_STATUS_VALUES = {
    PRE_REGISTERED_STATUS,
    REGISTERED_STATUS,
    QUOTED_STATUS,
    PAYMENT_CONFIRMED_STATUS,
    RECEIPT_ISSUED_STATUS,
    IN_TRANSIT_STATUS,
    AT_DESTINATION_STATUS,
    DELIVERED_STATUS,
    CANCELED_STATUS,
}

EDITABLE_STATUS_VALUES = {
    PRE_REGISTERED_STATUS,
    REGISTERED_STATUS,
}

INTERNAL_REGISTRATION_ORIGIN = "INTERNO"
EXTERNAL_REGISTRATION_ORIGIN = "EXTERNO"
REGISTRATION_ORIGIN_VALUES = {
    INTERNAL_REGISTRATION_ORIGIN,
    EXTERNAL_REGISTRATION_ORIGIN,
}

FRAGILITY_VALUES = {"BAJA", "MEDIA", "ALTA"}
