PRE_REGISTERED_STATUS = "PRE_REGISTRADA"
REGISTERED_STATUS = "REGISTRADA"
QUOTED_STATUS = "COTIZADA"
PAYMENT_CONFIRMED_STATUS = "PAGO_CONFIRMADO"
RECEIPT_ISSUED_STATUS = "BOLETA_EMITIDA"
IN_TRANSIT_STATUS = "EN_TRANSITO"
AT_DESTINATION_STATUS = "EN_DESTINO"
DELIVERED_STATUS = "ENTREGADA"
CANCELED_STATUS = "ANULADA"

SHIPMENT_STATUS_VALUES = {
    PRE_REGISTERED_STATUS,
    REGISTERED_STATUS,
    QUOTED_STATUS,
    PAYMENT_CONFIRMED_STATUS,
    RECEIPT_ISSUED_STATUS,
    IN_TRANSIT_STATUS,
    AT_DESTINATION_STATUS,
    DELIVERED_STATUS,
    CANCELED_STATUS,
}

EDITABLE_STATUS_VALUES = {
    PRE_REGISTERED_STATUS,
    REGISTERED_STATUS,
}

INTERNAL_REGISTRATION_ORIGIN = "INTERNO"
EXTERNAL_REGISTRATION_ORIGIN = "EXTERNO"
REGISTRATION_ORIGIN_VALUES = {
    INTERNAL_REGISTRATION_ORIGIN,
    EXTERNAL_REGISTRATION_ORIGIN,
}

FRAGILITY_VALUES = {"BAJA", "MEDIA", "ALTA"}

# Límites físicos del servicio, derivados de la capacidad del vehículo
# (491 x 210 x 220 cm, 5470 kg). Actúan como cota superior de sanidad: un peso o
# una dimensión por encima de estos valores no puede transportarse y casi siempre
# es un error de tipeo. El mínimo es estrictamente > 0 (ver validadores).
MAX_WEIGHT_KG = 5470.0
MAX_DIMENSION_CM = 491.0

# Un sobre (tipo_contenido DOCUMENTOS) no puede pesar mas de 1.5 kg: por encima de
# eso ya no es documentacion sino un paquete y debe registrarse como tal.
MAX_ENVELOPE_WEIGHT_KG = 1.5
