FIRST_FIT_3D = "FIRST_FIT_3D"
MINIMAX_MAXIMIN_3D = "MINIMAX_MAXIMIN_3D"
BEST_FIT_3D = "BEST_FIT_3D"
WORST_FIT = "WORST_FIT"
BEST_FIT_DECREASING_3D = "BEST_FIT_DECREASING_3D"
BACKTRACKING_LOGISTIC = "BACKTRACKING_LOGISTIC"
MINIMAX = "MINIMAX"
MAXIMIN = "MAXIMIN"

FRAGILITY_ORDER = {"ALTA": 0, "MEDIA": 1, "BAJA": 2}
STACK_PRIORITY = {"BAJA": 0, "MEDIA": 1, "ALTA": 2}

LOGISTIC_ROUTE = [
    "TRUJILLO",
    "SHOREY",
    "HUAYCATAN",
    "SANTIAGO DE CHUCO",
    "CHACOMAS",
    "CACHICADAN",
    "SANTA CRUZ",
    "COCHAPAMBA",
    "UGALLAMA",
    "VILLACRUZ",
    "LAS MANZANAS",
    "ANGASMARCA",
    "TAMBO PAMPAMARCA ALTA",
    "PSICOCHACA",
    "SANTA CLARA DE TULPO",
    "LA YEGUADA",
    "MOLLEBAMBA",
    "COCHAMARCA",
    "OROCULLAY",
]

DESTINATION_ALIASES = {
    "HUAYATAN": "HUAYCATAN",
    "SANTA CRUZ DE CHUCA": "SANTA CRUZ",
    "ALGALLAMA": "UGALLAMA",
}
ROUTE_RANK = {destination: index for index, destination in enumerate(LOGISTIC_ROUTE)}
MAX_ROUTE_RANK = max(ROUTE_RANK.values())
